// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2rDbLPrk1H3CamAVRM3iCdlhNnXZMm34',
    appId: '1:450237715056:web:c647eeb9b9fe84eba91ab5',
    messagingSenderId: '450237715056',
    projectId: 'caurse-app',
    authDomain: 'caurse-app.firebaseapp.com',
    storageBucket: 'caurse-app.appspot.com',
    measurementId: 'G-EC4L75WLKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASEwxwwSAxQlbSXIGt4KxPqBX9FvHRF04',
    appId: '1:450237715056:android:6a06b7ad8f9f8a1fa91ab5',
    messagingSenderId: '450237715056',
    projectId: 'caurse-app',
    storageBucket: 'caurse-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfFe8ZAmWTorEVXClPhy-B-jsTQGASKwU',
    appId: '1:450237715056:ios:5b3fe9fb4e51f2a5a91ab5',
    messagingSenderId: '450237715056',
    projectId: 'caurse-app',
    storageBucket: 'caurse-app.appspot.com',
    iosBundleId: 'com.example.transactionApp',
  );
}
